### ISSUE TITLE
Changing pwTemplateZipRelDir multiple times

### ISSUE THREAD

**Issue by mm98** [ligershark/pecan-waffle#38] opened 2016-05-14 19:21 UTC
When changing **pwTemplateZipRelDir** in **pecan-waffle-settings.props** multiple times, the VSIX (zip) contains "_VsTemplateProj1.project.zip_" in every previously defined location. 

I haven't been able to find where this information is stored.

**Comment by sayedihashimi** [comment] 2016-05-14 20:34
Thanks for the report. We will have to add a target to extend Clean to delete the files previously generated. Does this cause any errors besides seeing extra templates?

**Comment by mm98** [comment] 2016-05-14 20:50
No, this doesn't result in any errors. Only that the template exists in multiple locations in the VS "Create Project" window.

**Comment by mm98** [comment] 2016-05-14 20:52
This even happens when you do a Build > Clean (empty bin folder), so this historic information must be stored somewhere.

**Comment by sayedihashimi** [comment] 2016-05-14 22:10
@mm98 the info is not stored anywhere. The issue is that when you do a `Clean` the files are not deleted. To fix this we need to add a new target to https://github.com/ligershark/pecan-waffle/blob/master/pecan-waffle-vs.targets which extends Clean to delete the templates temp dir.

**Comment by sayedihashimi** [comment] 2016-05-16 07:08
@mm98 it should be fixed in the `0.0.22-beta` package. Let me know if you run into any issues with that. Closing this now.

**Closed as completed by sayedihashimi** 2016-05-16 07:08 UTC
Labels: bug

**Comment by mm98** [comment] 2016-05-16 08:59
I have updated the pecan project to `0.0.22-beta`. Two nodes were removed in `pecan-waffle-settings.props` (overwritten on package update).

When i Build the solution I get an error, that it can't find the ProjectId defined in `source.extension.vsixmanifest`. I have double checked, and the ProjectId's are the same in `source.extension.vsixmanifest` and `_project.vstemplate`. 

Do i need to make any changes to `_project.vstemplate` or `pw-templateinfo.ps1` ?

**Note**
The VSIX is created in the `bin`/`debug` folder and the VSIX is working when installing (#37).

**Error List output**
`Extension 'MultiProjectTemplate.Carsten Petersen.ef4a14f9-7ab6-4ede-8716-81ea0e1cee9a' could not be found. Please make sure the extension has been installed.  MultiProjectTemplate`

![screenshot_1](https://cloud.githubusercontent.com/assets/992714/15283708/e3d02b3a-1b4c-11e6-9774-217618324fc4.png)

**Comment by sayedihashimi** [comment] 2016-05-16 15:17
This is some weirdness wth the VS experimental instance I think. When you see this, try a Clean and then a Build.

**Comment by mm98** [comment] 2016-05-16 15:25
Helped when closing VS .. start project again and do a `Clean` before `Build`.
